### ISSUE TITLE
UnboundLocalError at /user/ local variable 'Token' referenced before assignment

### ISSUE THREAD

**Issue by philippeowagner** [3bot/3bot#24]
Can't remember - is the``Token`` required for the default 3bot installation or is it only required if https://github.com/3bot/3bot-hook is used?

**Comment by walterrenner** [comment]
It was not, but it is fixed sice https://github.com/3bot/3bot/commit/4e8bc3c753b91d1e707c8fe4abcefa2fff87eb00
