### ISSUE TITLE
IOError: write error

### ISSUE THREAD

**Issue by walterrenner** [3bot/3bot#42]
https://my.sentry.arteria.ch/arteria/my3botio/issues/1750/

```
IOError: write error

IOError: write error
```

**Comment by walterrenner** [comment]
Seit der Umstellung auf uwsgi triff dieser Fehler auf.

@philippeowagner ist die auch schon aufgefallen das manchmal die Startseite erst beim 2. oder 3. mal ladet?

**Comment by philippeowagner** [comment]
https://github.com/arteria/my-3bot/issues/29
